create table if not exists public.family_units (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  invite_code text unique not null,
  start_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  display_name text,
  active_family_id uuid references public.family_units on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.family_members (
  family_id uuid references public.family_units on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  role text check (role in ('cocinitas', 'miembro')) not null,
  primary key (family_id, user_id)
);

create or replace function public.handle_cocinitas_membership_deleted()
returns trigger as $$
declare
  affected_profile_id uuid;
begin
  if old.role <> 'cocinitas' then
    return old;
  end if;

  if exists (
    select 1
    from public.family_members
    where family_id = old.family_id
      and role = 'cocinitas'
  ) then
    return old;
  end if;

  for affected_profile_id in
    select p.id
    from public.profiles p
    where p.active_family_id = old.family_id
  loop
    update public.profiles p
    set active_family_id = (
      select fm.family_id
      from public.family_members fm
      where fm.user_id = p.id
        and fm.family_id <> old.family_id
      order by fm.family_id
      limit 1
    )
    where p.id = affected_profile_id;
  end loop;

  delete from public.family_units
  where id = old.family_id;

  return old;
end;
$$ language plpgsql;

drop trigger if exists on_cocinitas_membership_deleted on public.family_members;
create trigger on_cocinitas_membership_deleted
  after delete on public.family_members
  for each row execute procedure public.handle_cocinitas_membership_deleted();

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email, split_part(new.email, '@', 1));
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.pantry add column if not exists family_id uuid references public.family_units on delete cascade;
alter table public.shopping_list add column if not exists family_id uuid references public.family_units on delete cascade;

create table if not exists public.meal_plans (
  id bigint generated by default as identity primary key,
  family_id uuid references public.family_units on delete cascade not null,
  day integer not null,
  desayuno bigint references public.recipes(id) on delete set null,
  comida bigint references public.recipes(id) on delete set null,
  cena bigint references public.recipes(id) on delete set null,
  desayuno_slots jsonb not null default '[null]'::jsonb,
  comida_slots jsonb not null default '[null]'::jsonb,
  cena_slots jsonb not null default '[null]'::jsonb,
  unique (family_id, day)
);

alter table public.meal_plans add column if not exists desayuno_slots jsonb not null default '[null]'::jsonb;
alter table public.meal_plans add column if not exists comida_slots jsonb not null default '[null]'::jsonb;
alter table public.meal_plans add column if not exists cena_slots jsonb not null default '[null]'::jsonb;

update public.meal_plans
set
  desayuno_slots = case
    when jsonb_typeof(desayuno_slots) = 'array' and jsonb_array_length(desayuno_slots) > 0 then desayuno_slots
    when desayuno is not null then jsonb_build_array(desayuno)
    else '[null]'::jsonb
  end,
  comida_slots = case
    when jsonb_typeof(comida_slots) = 'array' and jsonb_array_length(comida_slots) > 0 then comida_slots
    when comida is not null then jsonb_build_array(comida)
    else '[null]'::jsonb
  end,
  cena_slots = case
    when jsonb_typeof(cena_slots) = 'array' and jsonb_array_length(cena_slots) > 0 then cena_slots
    when cena is not null then jsonb_build_array(cena)
    else '[null]'::jsonb
  end;

create table if not exists public.recipe_suggestions (
  id bigint generated by default as identity primary key,
  family_id uuid references public.family_units on delete cascade not null,
  day integer not null,
  meal_type text check (meal_type in ('desayuno', 'comida', 'cena')) not null,
  suggested_recipe_id bigint references public.recipes(id) on delete cascade not null,
  suggested_by uuid references public.profiles(id) on delete cascade not null,
  status text check (status in ('pendiente', 'aprobado', 'rechazado')) default 'pendiente' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.recipe_suggestion_votes (
  suggestion_id bigint references public.recipe_suggestions(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  vote text check (vote in ('like', 'dislike')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (suggestion_id, user_id)
);

create table if not exists public.family_notifications (
  id bigint generated by default as identity primary key,
  family_id uuid references public.family_units on delete cascade not null,
  recipient_user_id uuid references public.profiles(id) on delete cascade not null,
  actor_user_id uuid references public.profiles(id) on delete set null,
  title text not null,
  body text not null,
  read_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_family_notifications_recipient_read
  on public.family_notifications (recipient_user_id, read_at, created_at desc);

alter table public.family_units disable row level security;
alter table public.profiles disable row level security;
alter table public.family_members disable row level security;
alter table public.meal_plans disable row level security;
alter table public.recipe_suggestions disable row level security;
alter table public.recipe_suggestion_votes disable row level security;
alter table public.family_notifications disable row level security;
