create table if not exists public.family_units (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  invite_code text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  display_name text,
  active_family_id uuid references public.family_units on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.family_members (
  family_id uuid references public.family_units on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  role text check (role in ('cocinitas', 'miembro')) not null,
  primary key (family_id, user_id)
);

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email, split_part(new.email, '@', 1));
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.pantry add column if not exists family_id uuid references public.family_units on delete cascade;
alter table public.shopping_list add column if not exists family_id uuid references public.family_units on delete cascade;

create table if not exists public.meal_plans (
  id bigint generated by default as identity primary key,
  family_id uuid references public.family_units on delete cascade not null,
  day integer not null,
  desayuno bigint references public.recipes(id) on delete set null,
  comida bigint references public.recipes(id) on delete set null,
  cena bigint references public.recipes(id) on delete set null,
  unique (family_id, day)
);

create table if not exists public.recipe_suggestions (
  id bigint generated by default as identity primary key,
  family_id uuid references public.family_units on delete cascade not null,
  day integer not null,
  meal_type text check (meal_type in ('desayuno', 'comida', 'cena')) not null,
  suggested_recipe_id bigint references public.recipes(id) on delete cascade not null,
  suggested_by uuid references public.profiles(id) on delete cascade not null,
  status text check (status in ('pendiente', 'aprobado', 'rechazado')) default 'pendiente' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.family_units disable row level security;
alter table public.profiles disable row level security;
alter table public.family_members disable row level security;
alter table public.meal_plans disable row level security;
alter table public.recipe_suggestions disable row level security;
